language: csharp
solution: src/Redux.sln
install:
  - nuget restore src/Redux.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Redux.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Redux.Tests/bin/Release/Redux.Tests.dll